# Generated by Django 5.0.6 on 2024-06-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_ad_image_alter_ad_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
